# Generated by Django 4.2.27 on 2025-12-15 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Switch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('switch_id', models.IntegerField(unique=True)),
                ('switch_label', models.CharField(max_length=50)),
                ('switch_name', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['switch_label'],
            },
        ),
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terminal_id', models.IntegerField(unique=True)),
                ('terminal_code', models.CharField(max_length=50)),
                ('terminal_name', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['terminal_code'],
            },
        ),
    ]
