# Generated by Django 4.2.27 on 2025-12-15 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwitchTerminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('switch_id', models.IntegerField()),
                ('terminal_id', models.IntegerField()),
            ],
            options={
                'ordering': ['switch_id', 'terminal_id'],
                'unique_together': {('switch_id', 'terminal_id')},
            },
        ),
    ]
