# Generated by Django 4.2.27 on 2025-12-15 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_switchterminal'),
    ]

    operations = [
        migrations.CreateModel(
            name='TerminalStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('switch_terminal_id', models.IntegerField()),
                ('log_at', models.DateTimeField()),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['log_at', 'switch_terminal_id'],
                'unique_together': {('switch_terminal_id', 'log_at')},
            },
        ),
        migrations.CreateModel(
            name='SwitchStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('switch_id', models.IntegerField()),
                ('log_at', models.DateTimeField()),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['log_at', 'switch_id'],
                'unique_together': {('switch_id', 'log_at')},
            },
        ),
    ]
