# Generated by Django 4.2.27 on 2025-12-15 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_terminalstatus_switchstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwitchAlerts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('switch_id', models.IntegerField()),
                ('alert_type', models.CharField(max_length=50)),
                ('log_at', models.DateTimeField()),
                ('notified_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['notified_at', 'switch_id'],
            },
        ),
    ]
