# Generated by Django 4.2.27 on 2025-12-15 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_switchalerts'),
    ]

    operations = [
        migrations.AddField(
            model_name='switchstatus',
            name='switchobj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='devices.switch'),
        ),
    ]
