# Generated by Django 4.2.27 on 2025-12-16 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_switchstatus_switchobj'),
    ]

    operations = [
        migrations.AddField(
            model_name='switchalerts',
            name='switchobj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='devices.switch'),
        ),
    ]
