# Generated by Django 4.2.27 on 2025-12-16 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_switchalerts_switchobj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='switchalerts',
            name='switchobj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='devices.switch', to_field='switch_id'),
        ),
    ]
