# Generated by Django 4.2.27 on 2025-12-16 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0007_alter_switchalerts_switchobj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='switchalerts',
            name='switch_id',
            field=models.IntegerField(unique=True),
        ),
    ]
