# Generated by Django 4.2.27 on 2025-12-15 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_id', models.IntegerField(auto_created=True, unique=True)),
                ('switch_label', models.CharField(max_length=2)),
                ('t1', models.BooleanField(default=False)),
                ('t2', models.BooleanField(default=False)),
                ('t3', models.BooleanField(default=False)),
                ('t4', models.BooleanField(default=False)),
                ('t5', models.BooleanField(default=False)),
                ('logtime', models.DateTimeField(null=True)),
            ],
            options={
                'ordering': ['data_id'],
            },
        ),
    ]
