# Generated by Django 4.2.27 on 2025-12-15 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rawdata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rawdata',
            options={'ordering': ['logtime']},
        ),
        migrations.RemoveField(
            model_name='rawdata',
            name='data_id',
        ),
    ]
